// <auto-generated />
using System;
using MiBalance.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MiBalance.Infrastructure.Migrations
{
    [DbContext(typeof(MiBalanceDbContext))]
    partial class MiBalanceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MiBalance.Core.Entities.AsientoContable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Concepto")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<int?>("TransaccionId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Numero")
                        .IsUnique();

                    b.HasIndex("TransaccionId")
                        .IsUnique()
                        .HasFilter("[TransaccionId] IS NOT NULL");

                    b.ToTable("AsientosContables");
                });

            modelBuilder.Entity("MiBalance.Core.Entities.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CategoriaPadreId")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Icono")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaPadreId");

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "#FF5733",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Nombre = "Servicios Básicos",
                            Tipo = 1
                        },
                        new
                        {
                            Id = 2,
                            Color = "#33FF57",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Nombre = "Alimentación",
                            Tipo = 2
                        },
                        new
                        {
                            Id = 3,
                            Color = "#3357FF",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Nombre = "Transporte",
                            Tipo = 2
                        },
                        new
                        {
                            Id = 4,
                            Color = "#FFD700",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Nombre = "Salario",
                            Tipo = 3
                        },
                        new
                        {
                            Id = 5,
                            Color = "#FF33F5",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Nombre = "Entretenimiento",
                            Tipo = 2
                        });
                });

            modelBuilder.Entity("MiBalance.Core.Entities.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Identificacion")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Relacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("MiBalance.Core.Entities.CuentaContable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CuentaPadreId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EsDeMovimiento")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("Naturaleza")
                        .HasColumnType("int");

                    b.Property<int>("Nivel")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("CuentaPadreId");

                    b.ToTable("CuentasContables");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Codigo = "1",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EsDeMovimiento = false,
                            IsActive = true,
                            Naturaleza = 1,
                            Nivel = 1,
                            Nombre = "ACTIVO",
                            Tipo = 1
                        },
                        new
                        {
                            Id = 2,
                            Codigo = "1.1",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CuentaPadreId = 1,
                            EsDeMovimiento = false,
                            IsActive = true,
                            Naturaleza = 1,
                            Nivel = 2,
                            Nombre = "ACTIVO CORRIENTE",
                            Tipo = 1
                        },
                        new
                        {
                            Id = 3,
                            Codigo = "1.1.1",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CuentaPadreId = 2,
                            EsDeMovimiento = true,
                            IsActive = true,
                            Naturaleza = 1,
                            Nivel = 3,
                            Nombre = "Efectivo y Equivalentes",
                            Tipo = 1
                        },
                        new
                        {
                            Id = 4,
                            Codigo = "1.1.2",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CuentaPadreId = 2,
                            EsDeMovimiento = true,
                            IsActive = true,
                            Naturaleza = 1,
                            Nivel = 3,
                            Nombre = "Cuentas por Cobrar",
                            Tipo = 1
                        },
                        new
                        {
                            Id = 5,
                            Codigo = "2",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EsDeMovimiento = false,
                            IsActive = true,
                            Naturaleza = 2,
                            Nivel = 1,
                            Nombre = "PASIVO",
                            Tipo = 2
                        },
                        new
                        {
                            Id = 6,
                            Codigo = "2.1",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CuentaPadreId = 5,
                            EsDeMovimiento = false,
                            IsActive = true,
                            Naturaleza = 2,
                            Nivel = 2,
                            Nombre = "PASIVO CORRIENTE",
                            Tipo = 2
                        },
                        new
                        {
                            Id = 7,
                            Codigo = "2.1.1",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CuentaPadreId = 6,
                            EsDeMovimiento = true,
                            IsActive = true,
                            Naturaleza = 2,
                            Nivel = 3,
                            Nombre = "Cuentas por Pagar",
                            Tipo = 2
                        },
                        new
                        {
                            Id = 8,
                            Codigo = "2.1.2",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CuentaPadreId = 6,
                            EsDeMovimiento = true,
                            IsActive = true,
                            Naturaleza = 2,
                            Nivel = 3,
                            Nombre = "Tarjetas de Crédito",
                            Tipo = 2
                        },
                        new
                        {
                            Id = 9,
                            Codigo = "3",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EsDeMovimiento = false,
                            IsActive = true,
                            Naturaleza = 2,
                            Nivel = 1,
                            Nombre = "PATRIMONIO",
                            Tipo = 3
                        },
                        new
                        {
                            Id = 10,
                            Codigo = "3.1",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CuentaPadreId = 9,
                            EsDeMovimiento = true,
                            IsActive = true,
                            Naturaleza = 2,
                            Nivel = 2,
                            Nombre = "Capital",
                            Tipo = 3
                        },
                        new
                        {
                            Id = 11,
                            Codigo = "4",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EsDeMovimiento = false,
                            IsActive = true,
                            Naturaleza = 2,
                            Nivel = 1,
                            Nombre = "INGRESOS",
                            Tipo = 4
                        },
                        new
                        {
                            Id = 12,
                            Codigo = "4.1",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CuentaPadreId = 11,
                            EsDeMovimiento = false,
                            IsActive = true,
                            Naturaleza = 2,
                            Nivel = 2,
                            Nombre = "Ingresos Operacionales",
                            Tipo = 4
                        },
                        new
                        {
                            Id = 13,
                            Codigo = "4.1.1",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CuentaPadreId = 12,
                            EsDeMovimiento = true,
                            IsActive = true,
                            Naturaleza = 2,
                            Nivel = 3,
                            Nombre = "Salarios",
                            Tipo = 4
                        },
                        new
                        {
                            Id = 14,
                            Codigo = "5",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EsDeMovimiento = false,
                            IsActive = true,
                            Naturaleza = 1,
                            Nivel = 1,
                            Nombre = "GASTOS",
                            Tipo = 5
                        },
                        new
                        {
                            Id = 15,
                            Codigo = "5.1",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CuentaPadreId = 14,
                            EsDeMovimiento = false,
                            IsActive = true,
                            Naturaleza = 1,
                            Nivel = 2,
                            Nombre = "Gastos Fijos",
                            Tipo = 5
                        },
                        new
                        {
                            Id = 16,
                            Codigo = "5.1.1",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CuentaPadreId = 15,
                            EsDeMovimiento = true,
                            IsActive = true,
                            Naturaleza = 1,
                            Nivel = 3,
                            Nombre = "Servicios Básicos",
                            Tipo = 5
                        },
                        new
                        {
                            Id = 17,
                            Codigo = "5.2",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CuentaPadreId = 14,
                            EsDeMovimiento = false,
                            IsActive = true,
                            Naturaleza = 1,
                            Nivel = 2,
                            Nombre = "Gastos Variables",
                            Tipo = 5
                        },
                        new
                        {
                            Id = 18,
                            Codigo = "5.2.1",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CuentaPadreId = 17,
                            EsDeMovimiento = true,
                            IsActive = true,
                            Naturaleza = 1,
                            Nivel = 3,
                            Nombre = "Alimentación",
                            Tipo = 5
                        });
                });

            modelBuilder.Entity("MiBalance.Core.Entities.CuentaPorCobrar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaPrestamo")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaVencimiento")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal>("MontoOriginal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MontoPendiente")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("TasaInteres")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("CuentasPorCobrar");
                });

            modelBuilder.Entity("MiBalance.Core.Entities.CuentaPorPagar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaEmision")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaVencimiento")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("InteresesMora")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal>("MontoOriginal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MontoPendiente")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("NumeroFactura")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProveedorId")
                        .HasColumnType("int");

                    b.Property<int?>("TarjetaId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ProveedorId");

                    b.HasIndex("TarjetaId");

                    b.ToTable("CuentasPorPagar");
                });

            modelBuilder.Entity("MiBalance.Core.Entities.DetalleAsiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AsientoContableId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CuentaContableId")
                        .HasColumnType("int");

                    b.Property<decimal>("Debe")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Haber")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AsientoContableId");

                    b.HasIndex("CuentaContableId");

                    b.ToTable("DetallesAsientos");
                });

            modelBuilder.Entity("MiBalance.Core.Entities.PagoCuenta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CuentaPorCobrарId")
                        .HasColumnType("int");

                    b.Property<int?>("CuentaPorPagarId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaPago")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Referencia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TransaccionId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CuentaPorCobrарId");

                    b.HasIndex("CuentaPorPagarId");

                    b.HasIndex("TransaccionId");

                    b.ToTable("PagosCuentas");
                });

            modelBuilder.Entity("MiBalance.Core.Entities.Proveedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("RUC")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Proveedores");
                });

            modelBuilder.Entity("MiBalance.Core.Entities.Recordatorio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CuentaPorCobrarId")
                        .HasColumnType("int");

                    b.Property<int?>("CuentaPorPagarId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Enviado")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaEnvio")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaRecordatorio")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("TransaccionId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CuentaPorCobrarId");

                    b.HasIndex("CuentaPorPagarId");

                    b.HasIndex("TransaccionId");

                    b.ToTable("Recordatorios");
                });

            modelBuilder.Entity("MiBalance.Core.Entities.Tarjeta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Banco")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DiaCorte")
                        .HasColumnType("int");

                    b.Property<int>("DiaPago")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal?>("LimiteCredito")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<string>("Titular")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UltimosDigitos")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Tarjetas");
                });

            modelBuilder.Entity("MiBalance.Core.Entities.Transaccion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<int?>("ClienteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("NotasIA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroDocumento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Origen")
                        .HasColumnType("int");

                    b.Property<int?>("ProveedorId")
                        .HasColumnType("int");

                    b.Property<int?>("TarjetaId")
                        .HasColumnType("int");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("ClienteId");

                    b.HasIndex("ProveedorId");

                    b.HasIndex("TarjetaId");

                    b.ToTable("Transacciones");
                });

            modelBuilder.Entity("MiBalance.Core.Entities.AsientoContable", b =>
                {
                    b.HasOne("MiBalance.Core.Entities.Transaccion", "Transaccion")
                        .WithOne("AsientoContable")
                        .HasForeignKey("MiBalance.Core.Entities.AsientoContable", "TransaccionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Transaccion");
                });

            modelBuilder.Entity("MiBalance.Core.Entities.Categoria", b =>
                {
                    b.HasOne("MiBalance.Core.Entities.Categoria", "CategoriaPadre")
                        .WithMany("SubCategorias")
                        .HasForeignKey("CategoriaPadreId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CategoriaPadre");
                });

            modelBuilder.Entity("MiBalance.Core.Entities.CuentaContable", b =>
                {
                    b.HasOne("MiBalance.Core.Entities.CuentaContable", "CuentaPadre")
                        .WithMany("SubCuentas")
                        .HasForeignKey("CuentaPadreId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CuentaPadre");
                });

            modelBuilder.Entity("MiBalance.Core.Entities.CuentaPorCobrar", b =>
                {
                    b.HasOne("MiBalance.Core.Entities.Cliente", "Cliente")
                        .WithMany("CuentasPorCobrar")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("MiBalance.Core.Entities.CuentaPorPagar", b =>
                {
                    b.HasOne("MiBalance.Core.Entities.Proveedor", "Proveedor")
                        .WithMany()
                        .HasForeignKey("ProveedorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MiBalance.Core.Entities.Tarjeta", "Tarjeta")
                        .WithMany()
                        .HasForeignKey("TarjetaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Proveedor");

                    b.Navigation("Tarjeta");
                });

            modelBuilder.Entity("MiBalance.Core.Entities.DetalleAsiento", b =>
                {
                    b.HasOne("MiBalance.Core.Entities.AsientoContable", "AsientoContable")
                        .WithMany("Detalles")
                        .HasForeignKey("AsientoContableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MiBalance.Core.Entities.CuentaContable", "CuentaContable")
                        .WithMany("DetallesAsientos")
                        .HasForeignKey("CuentaContableId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AsientoContable");

                    b.Navigation("CuentaContable");
                });

            modelBuilder.Entity("MiBalance.Core.Entities.PagoCuenta", b =>
                {
                    b.HasOne("MiBalance.Core.Entities.CuentaPorCobrar", "CuentaPorCobrar")
                        .WithMany("Pagos")
                        .HasForeignKey("CuentaPorCobrарId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MiBalance.Core.Entities.CuentaPorPagar", "CuentaPorPagar")
                        .WithMany("Pagos")
                        .HasForeignKey("CuentaPorPagarId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MiBalance.Core.Entities.Transaccion", "Transaccion")
                        .WithMany()
                        .HasForeignKey("TransaccionId");

                    b.Navigation("CuentaPorCobrar");

                    b.Navigation("CuentaPorPagar");

                    b.Navigation("Transaccion");
                });

            modelBuilder.Entity("MiBalance.Core.Entities.Recordatorio", b =>
                {
                    b.HasOne("MiBalance.Core.Entities.CuentaPorCobrar", "CuentaPorCobrar")
                        .WithMany()
                        .HasForeignKey("CuentaPorCobrarId");

                    b.HasOne("MiBalance.Core.Entities.CuentaPorPagar", "CuentaPorPagar")
                        .WithMany()
                        .HasForeignKey("CuentaPorPagarId");

                    b.HasOne("MiBalance.Core.Entities.Transaccion", "Transaccion")
                        .WithMany("Recordatorios")
                        .HasForeignKey("TransaccionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CuentaPorCobrar");

                    b.Navigation("CuentaPorPagar");

                    b.Navigation("Transaccion");
                });

            modelBuilder.Entity("MiBalance.Core.Entities.Transaccion", b =>
                {
                    b.HasOne("MiBalance.Core.Entities.Categoria", "Categoria")
                        .WithMany("Transacciones")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MiBalance.Core.Entities.Cliente", "Cliente")
                        .WithMany("Transacciones")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MiBalance.Core.Entities.Proveedor", "Proveedor")
                        .WithMany("Transacciones")
                        .HasForeignKey("ProveedorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MiBalance.Core.Entities.Tarjeta", "Tarjeta")
                        .WithMany("Transacciones")
                        .HasForeignKey("TarjetaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Categoria");

                    b.Navigation("Cliente");

                    b.Navigation("Proveedor");

                    b.Navigation("Tarjeta");
                });

            modelBuilder.Entity("MiBalance.Core.Entities.AsientoContable", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("MiBalance.Core.Entities.Categoria", b =>
                {
                    b.Navigation("SubCategorias");

                    b.Navigation("Transacciones");
                });

            modelBuilder.Entity("MiBalance.Core.Entities.Cliente", b =>
                {
                    b.Navigation("CuentasPorCobrar");

                    b.Navigation("Transacciones");
                });

            modelBuilder.Entity("MiBalance.Core.Entities.CuentaContable", b =>
                {
                    b.Navigation("DetallesAsientos");

                    b.Navigation("SubCuentas");
                });

            modelBuilder.Entity("MiBalance.Core.Entities.CuentaPorCobrar", b =>
                {
                    b.Navigation("Pagos");
                });

            modelBuilder.Entity("MiBalance.Core.Entities.CuentaPorPagar", b =>
                {
                    b.Navigation("Pagos");
                });

            modelBuilder.Entity("MiBalance.Core.Entities.Proveedor", b =>
                {
                    b.Navigation("Transacciones");
                });

            modelBuilder.Entity("MiBalance.Core.Entities.Tarjeta", b =>
                {
                    b.Navigation("Transacciones");
                });

            modelBuilder.Entity("MiBalance.Core.Entities.Transaccion", b =>
                {
                    b.Navigation("AsientoContable");

                    b.Navigation("Recordatorios");
                });
#pragma warning restore 612, 618
        }
    }
}
